### ISSUE TITLE
Consider modernizing and refreshing the crate

### ISSUE THREAD

**Issue by BlackHoleFox** [badboy/signify-rs#29]
Hi, thanks for making this crate.

I had a project idea that signify would fit perfect in (software distribution handling), and I'd love to use the crate. However, a lot of things have bit-rotted away over the last 4-5 years.

Since I'd like to use it and would rather not fragment the crate ecosystem by making a second implementation, I'd like to open a set of PRs that update the crate and generally refresh it with modern Rust.

The end goal of this would be splitting up the crate into a binary and library, so that it can be embedded into other projects without a CLI tool.

**Comment by badboy** [comment]
Thanks for taking up that work. I merged all open PRs and about to add working CI again (#35).
As I have limited time (and currently no immediate use for signify) I would like to give you maintainer permissions here if that's ok with you.

**Comment by BlackHoleFox** [comment]
Thanks for fixing CI up :D

> I would like to give you maintainer permissions here if that's ok with you.

I'm fine with this and would be pleased to help out with maintainership.

**Comment by badboy** [comment]
Invite sent!
Please do go through PRs for changes and ping me for larger ones, I'm trying to be quick on review then.
When you feel like a new release should be done, ping me as well and I give it a look and will do a release.
If that's all going good I'll give you release permissions as well.

**Comment by BlackHoleFox** [comment]
Invite accepted :)

That all sounds good to me. Should be able to get back to working on this issue Saturday.
