### ISSUE TITLE
possible to include examples of libsignify usage?

### ISSUE THREAD

**Issue by ghost** [badboy/signify-rs#51]
would it be possible to get examples, in the readme or dedicated `examples/` directory, of using libsignify to validate files using a given pub key please? digging through the source is ok, but a concise example could be helpful too.

**Comment by BlackHoleFox** [comment]
Thanks for the idea :) This sounds reasonable to me. I actually intended for the `signify` CLI here to serve as that example but looking back on that idea now seems weird.

I'll try and put an example up that does "the whole flow" for inspiration.

**Comment by ghost** [comment]
thanks! if it helps, context from my case: i was trying to use [ureq](https://lib.rs/crates/ureq) to grab say the `SHA256.sig` file or a set and verify it as a simple test

**Comment by ghost** [comment]
i managed to sort of get a working example based on reading the source but it wasnt easy.

https://github.com/badboy/signify-rs/blob/main/signify/src/main.rs#L143-L149
this code also resulted in type errors from the `.map()` and `.map_err()` for me so i had to just remove those methods .

**Comment by BlackHoleFox** [comment]
I'm super sorry this one got dropped onto the floor. I kept meaning to put something up but always got sidetracked. Does #55 contain what you think you'd need to start again from scratch?

**Comment by ghost** [comment]
@BlackHoleFox no worries on the delays! that looks good to me yeah and makes sense. i did have to look up why you had a `_` in parenthesis but it makes sense to me. thanks for adding the basic example to the docs too
