### ISSUE TITLE
unknown type error during compilation

### ISSUE THREAD

**Issue by ghost** [badboy/signify-rs#52]
when trying to compile a program using `libsignify` i am getting an error about an unknown type (included below). what type should this be in the code? i was just trying to replicate the `verify()` from `signify-rs` in a small program.

rustc version:
```
> rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

error:
```
error[E0282]: type annotations needed
   --> D:\<MYUSER>\.cargo\registry\src\github.com-1ecc6299db9ec823\libsignify-0.5.2\src\key.rs:176:42
    |
176 |         checksum.copy_from_slice(&digest.as_ref()[0..8]);
    |                                   -------^^^^^^--
    |                                   |      |
    |                                   |      cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                   this method call resolves to `&T`
    |
    = note: type must be known at this point

For more information about this error, try `rustc --explain E0282`.
```

**Comment by BlackHoleFox** [comment]
Many thanks for the report. Seems like some downstream dependencies in your lockfile are newer than what CI here runs against and a change broke type inference. This should be fixed on `main` soon.

**Comment by ghost** [comment]
@BlackHoleFox sorry i know this is closed. i just tried to `cargo install signify` and got the same errors. maybe a new release is needed to pick up the changes from #53 ?

**Comment by BlackHoleFox** [comment]
Heyo. I'll look at getting a new release out soon once https://github.com/badboy/signify-rs/issues/51 is closed too, so probably tomorrow.

**Comment by BlackHoleFox** [comment]
@portno12 0.5.3 was just published with the fix (and example). `cargo release -p libsignify` should be what you need.
