### ISSUE TITLE
maintenance status?

### ISSUE THREAD

**Issue by unrushed-boots** [badboy/signify-rs#62]
i see some old open issues in the repo and no releases for a bit. is this still maintained, maybe adding dependabot would help with dep updates and issues?

**Comment by badboy** [comment]
I'm still around. I did a release just a month ago. All open issues are more feature requests; thus not a lot of priority for me.
Dependabot will just cause MORE work, which is even less likely to get done ;)

Some projects are sometimes just close to "done", they don't need constant work all the time.

**Comment by BlackHoleFox** [comment]
Yeah to say some of the same I'm happy to review PRs for implementing mentioned feature requests but life is busy enough these days I don't have the time to clear them out myself.
